#!/bin/sh
 
xsetroot -cursor_name left_ptr &
#dunst &
#mpd-notify &
#xautolock -time 10 -locker slimlock &
hsetroot -add '#848484' -add '#1d1f21' -gradient '0'
xset -b & #For annoying beeping sounds
sxhkd & 
picom &
exec ~/.config/polybar/launch.sh &
exec ~/.config/scripts/borders &

 
bspc monitor -d One Two Three Four Five Six
 
bspc config border_width         2
bspc config window_gap          25
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding        20

bspc rule -a Firefox state=floating
bspc rule -a Virt-manager state=floating
bspc rule -a Virt-Manager state=floating
bspc rule -a rofi state=floating
bspc rule -a * state=floating
bspc rule -a kitty state=floating
bspc rule -a virt-manager state=floating
bspc rule -a firefox state=floating
bspc rule -a gimp state=floating
bspc rule -a Gimp state=floating
bspc rule -a Feh state=floating
bspc rule -a feh state=floating
 
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#bspc config normal_border_color '#000000'
#bspc config active_border_color '#000000'
#bspc config focused_border_color '#000000'
